### ISSUE TITLE
Code style

### ISSUE THREAD

**Issue by CrazyPython** [tqdm/tqdm.cpp#10]
Let's establish what code style we should use.

Coming from a Python background, I prefer K&R braces. From the little C++ code I've seen @casperdcl write, it looks as though he does too.

So what do you guys think?

**Comment by casperdcl** [comment]
https://google.github.io/styleguide/cppguide.html

**Comment by casperdcl** [comment]
BTW I would just use http://clang.llvm.org/docs/ClangFormat.html which is like `flake8` but fixes rather than just suggesting.

**Comment by o11c** [comment]
Google's style guide is universally recognized as terrible among C++ programmers ...

**Comment by CrazyPython** [comment]
@o11c what should we use then? I like K&R braces coming from Python. It saves lines too.

**Comment by CrazyPython** [comment]
@casperdcl poke poke

**Comment by o11c** [comment]
Saving lines is an insignificant measurement. Being able to properly keep diffs through history is very important.

**Comment by CrazyPython** [comment]
@o11c Okay, but it increases code bulk

**Comment by casperdcl** [comment]
visual studio supports clang-format with -style=Google, and obviously so do all unix operating systems. I'd set your editors to use it and forget about it. We could spend ages arguing about double space versus 4 space versus tab, but imho it's not worth it.

**Comment by CrazyPython** [comment]
@casperdcl he was talking about diffs

**Comment by CrazyPython** [comment]
@casperdcl @o11c says Google's coding style is universally agreed upon by C++ programmers to be a bad style. I'm not sure how true that statement is, but I think we should have another look at this issue.

**Comment by casperdcl** [comment]
closed as this is a subset of discussion in #11. feel like opening an issue saying stop opening so many issues.
