### ISSUE TITLE
CONTRIBUTING.md

### ISSUE THREAD

**Issue by CrazyPython** [tqdm/tqdm.cpp#11]
- [ ] Mention code style agreed upon [here](https://github.com/tqdm/tqdm.cpp/issues/10)
- [x] Add a link to the chat room, whatever chat platform we agree upon

This issue shall stay open even after #20 is merged, since PR won't give us a full and proper contrib.md.

**Comment by casperdcl** [comment]
code style LLVM now, see .clang-format file. @o11c I've some options explicitly specified in the .clang-format file because I thought those were the ones we may debate on changing. let me know if you have any thoughts on that.
