### ISSUE TITLE
Chat room?

### ISSUE THREAD

**Issue by CrazyPython** [tqdm/tqdm.cpp#15]
Some issues are just too small to be discussed in issues or pull requests. A chat room feels like it would be useful just to KISS and to discuss small issues. An auditory ping is good for quick-contact. Tell me if you think this is a good idea. Candidates:

 - chat.stackexchange.com - not related to stack exchange or anything, but it's a good chat platform with audible pings. This has been done before with other projects. A large area for chatting and a cool starboard. Minimalistic. 
 - gitter - seems like a decent candidate. Maxamalistic (yes, just coined a new term)
 - slack - too private

A temporary SE chat room has been created [here.](http://chat.stackexchange.com/rooms/43704/tqdm-cpp)

**Comment by casperdcl** [comment]
+++++1 (aka +5) I'm sick of email notifications on this but don't want to
turn them off.

**Comment by CrazyPython** [comment]
Great to know!

@casperdcl Disable email notifications and regularly visit github.com, also chat could solve this too

**Comment by CrazyPython** [comment]
so gitter, or chat.stackexchange.com? gitter has better issue referencing stuff but chat.stackexchange.com is more casual and live. I'm leaning to an ad-hoc SE room. In fact, I'm gonna create a temporary one right now.

**Comment by o11c** [comment]
Personally I'm fond of IRC - among other reasons, it's the only thing besides email that *everyone* (CI notifications, etc) can agree to support.

My bouncer is down right now though ...

**Comment by CrazyPython** [comment]
@o11c IRC doesn't have the features of issue referencing or a starboard...

Here's the link to the SE room I made: http://chat.stackexchange.com/rooms/43704/tqdm-cpp

**Comment by o11c** [comment]
a chatroom is not *supposed* to be permanent.

And URLs and bots exist.

**Comment by CrazyPython** [comment]
@o11c eh, GitHub is permanent too. I really like auditory pings because it makes everything more asynchronous. Don't forget to KISS.

**Comment by CrazyPython** [comment]
@casperdcl Please. Join. On. Chat. Room.
