### ISSUE TITLE
Issues on wip branch

### ISSUE THREAD

**Issue by CrazyPython** [tqdm/tqdm.cpp#18]
@casperdcl Some issues I found:

 - Let's make it by default that you can directly pass an iterable to  `tqdm::tqdm()`, giving an end pointer is old school. You can overload the function.
 - In the README, use `auto&& i` to make it more general.
 - Authors section: let's not include that right now or include other contributors, like @o11c or me.
 - Spelling error in "Licence". 
 - Broken links for Screenshot and License.

**Comment by CrazyPython** [comment]
@casperdcl also please give o11c write access

**Comment by casperdcl** [comment]
- removed authors, good spot
- fixed links
- why `auto &&`?
- definitely will be overloading, start and end pointers was just an example

**Comment by CrazyPython** [comment]
@casperdcl 

- In example, don't use start and end pointers. Show the simplicity of tqdm and pass a single argument.
- It's more general and modern. It also allows easier copy-pasting. If I remember correctly, `auto&&` is the default way to use auto + iterate-range
- join us in chat - it's more asynchronous. Took a full six minutes for you to find this issue - chat gives you an auditory signal
- make a PR first wait a while to see if anybody raises any concerns before merging. a dev branch is nice, too.

**Comment by CrazyPython** [comment]
fixed the spelling mistake and added a link to the original project.

**Comment by CrazyPython** [comment]
@casperdcl updates?
