### ISSUE TITLE
Super simple range implementation

### ISSUE THREAD

**Issue by CrazyPython** [tqdm/tqdm.cpp#32]
C++14 'cause I don't know the return type of `tqdm::tqdm`.
```
auto inline range(int n) {
    return tqdm::tqdm(std::vector<int>({0, ..., n - 1}));
}
```

`inline` is important so that people can use range without losing any speed.

Also @casperdcl looks like it's just me and you for the next couple days... maybe we should work on that ad to get another dev?

**Comment by casperdcl** [comment]
no, range generator (already implemented) much more preferable to range iterator.

**Comment by CrazyPython** [comment]
@casperdcl huh? this is just a shorthand...
