### ISSUE TITLE
Third-Party libraries

### ISSUE THREAD

**Issue by CrazyPython** [tqdm/tqdm.cpp#5]
Should we use third-party like Boost? It makes it harder for the end-user to use, and for that reason I lean towards thinking we shouldn't use them if we can avoid it. Just my opinion though. So what do you guys think?

**Comment by o11c** [comment]
If we implement C++98 mode (I'm not convinced we need to, it's `$CURRENTYEAR` already), Boost will be practically required.

For C++11, I don't anticipate any need.

**Comment by CrazyPython** [comment]
@o11c Agreed. 

 - Don't use C++14 features because not everyone supports it.
 - Porting to C++98 can be a lower-priority issue just to satisfy those who need to work with older systems. We should get v1.0 up and running before we start with C++98.
 - Adding a feature to C++11 version shouldn't entail adding the feature to C++98. 
 - Sacrificing performance or simplicity is possible for C++98. 

So let's not use boost for the main implementation but use it for C++98. Sounds good?

**Comment by CrazyPython** [comment]
@o11c can close?

**Comment by CrazyPython** [comment]
@casperdcl  unrelated but, since you're online, can you join us in chat? gotta few things to discuss http://chat.stackexchange.com/rooms/43704/tqdm-cpp
